TARGET_BOOT_ANIMATION_RES := 1080
TARGET_SCREEN_HEIGHT := 2400
TARGET_SCREEN_WIDTH := 1080

CUSTOM_BUILDTYPE := OFFICIAL
CUSTOM_MAINTAINER := PaperBoy
TARGET_FACE_UNLOCK_SUPPORTED := true

TARGET_SUPPORTS_OMX_SERVICE := false
